export const ZONES = {
  A: { label: 'Uretim Hatti A', color: '#3B82F6' },
  B: { label: 'Uretim Hatti B', color: '#8B5CF6' },
  C: { label: 'Montaj Alani', color: '#06B6D4' },
  D: { label: 'Kalite Kontrol', color: '#10B981' },
};

export const MACHINES = [
  {
    id: 'cnc-01',
    name: 'CNC Freze #1',
    type: 'cnc',
    zone: 'A',
    position: { x: 120, y: 180 },
    sensors: ['vibration', 'temperature', 'sound', 'magnetic'],
    baselines: { vibration: 4.5, temperature: 62, humidity: 40, sound: 78, magnetic: 15 },
  },
  {
    id: 'cnc-02',
    name: 'CNC Torna #2',
    type: 'cnc',
    zone: 'A',
    position: { x: 320, y: 140 },
    sensors: ['vibration', 'temperature', 'sound'],
    baselines: { vibration: 5.2, temperature: 58, humidity: 38, sound: 82, magnetic: 12 },
  },
  {
    id: 'press-01',
    name: 'Hidrolik Pres',
    type: 'press',
    zone: 'A',
    position: { x: 520, y: 200 },
    sensors: ['vibration', 'temperature', 'sound', 'humidity'],
    baselines: { vibration: 6.8, temperature: 55, humidity: 45, sound: 92, magnetic: 8 },
  },
  {
    id: 'robot-01',
    name: 'Robot Kol #1',
    type: 'robot-arm',
    zone: 'B',
    position: { x: 180, y: 380 },
    sensors: ['vibration', 'temperature', 'magnetic'],
    baselines: { vibration: 2.1, temperature: 42, humidity: 35, sound: 55, magnetic: 22 },
  },
  {
    id: 'robot-02',
    name: 'Robot Kol #2',
    type: 'robot-arm',
    zone: 'B',
    position: { x: 380, y: 340 },
    sensors: ['vibration', 'temperature', 'magnetic', 'sound'],
    baselines: { vibration: 2.4, temperature: 44, humidity: 36, sound: 52, magnetic: 20 },
  },
  {
    id: 'conv-01',
    name: 'Konveyor Bant',
    type: 'conveyor',
    zone: 'B',
    position: { x: 580, y: 360 },
    sensors: ['vibration', 'temperature', 'sound'],
    baselines: { vibration: 3.5, temperature: 38, humidity: 50, sound: 68, magnetic: 5 },
  },
  {
    id: 'comp-01',
    name: 'Kompresor',
    type: 'compressor',
    zone: 'C',
    position: { x: 750, y: 180 },
    sensors: ['vibration', 'temperature', 'sound', 'humidity'],
    baselines: { vibration: 7.2, temperature: 72, humidity: 30, sound: 95, magnetic: 10 },
  },
  {
    id: 'weld-01',
    name: 'Kaynak Robotu',
    type: 'welder',
    zone: 'C',
    position: { x: 750, y: 360 },
    sensors: ['vibration', 'temperature', 'sound', 'magnetic'],
    baselines: { vibration: 3.8, temperature: 85, humidity: 25, sound: 88, magnetic: 35 },
  },
  {
    id: 'pack-01',
    name: 'Paketleme',
    type: 'packaging',
    zone: 'D',
    position: { x: 920, y: 200 },
    sensors: ['vibration', 'temperature', 'humidity'],
    baselines: { vibration: 1.8, temperature: 32, humidity: 55, sound: 62, magnetic: 3 },
  },
  {
    id: 'pump-01',
    name: 'Hidrolik Pompa',
    type: 'pump',
    zone: 'D',
    position: { x: 920, y: 380 },
    sensors: ['vibration', 'temperature', 'sound', 'humidity'],
    baselines: { vibration: 5.5, temperature: 65, humidity: 42, sound: 85, magnetic: 7 },
  },
];

export const SENSOR_CONFIG = {
  vibration: {
    label: 'Titresim',
    unit: 'mm/s',
    icon: 'Activity',
    color: '#EF4444',
    max: 15,
    gaugeMax: 15,
    thresholds: { warning: 50, critical: 75 },
    range: { min: 0.5, max: 12 },
  },
  temperature: {
    label: 'Sicaklik',
    unit: '\u00B0C',
    icon: 'Thermometer',
    color: '#F59E0B',
    max: 100,
    gaugeMax: 100,
    thresholds: { warning: 65, critical: 85 },
    range: { min: 18, max: 95 },
  },
  humidity: {
    label: 'Nem',
    unit: '%RH',
    icon: 'Droplets',
    color: '#3B82F6',
    max: 100,
    gaugeMax: 100,
    thresholds: { warning: 70, critical: 90 },
    range: { min: 20, max: 90 },
  },
  sound: {
    label: 'Ses',
    unit: 'dB',
    icon: 'Volume2',
    color: '#8B5CF6',
    max: 120,
    gaugeMax: 120,
    thresholds: { warning: 65, critical: 80 },
    range: { min: 30, max: 110 },
  },
  magnetic: {
    label: 'Manyetik',
    unit: 'mT',
    icon: 'Magnet',
    color: '#06B6D4',
    max: 60,
    gaugeMax: 60,
    thresholds: { warning: 60, critical: 85 },
    range: { min: 0.1, max: 50 },
  },
};

export const CONNECTION_LINES = [
  { from: 'cnc-01', to: 'cnc-02' },
  { from: 'cnc-02', to: 'press-01' },
  { from: 'press-01', to: 'comp-01' },
  { from: 'robot-01', to: 'robot-02' },
  { from: 'robot-02', to: 'conv-01' },
  { from: 'conv-01', to: 'pack-01' },
  { from: 'comp-01', to: 'weld-01' },
  { from: 'weld-01', to: 'pump-01' },
];
